Update XLTS dependencies
xlts-dev/angularjs-webpack-babel pull request #1
Opened 2022-01-13 19:56 UTC by edclement

## Changes
* Updates the XLTS for AngularJS dependencies to `1.8.7`
* Update the `.npmrc` file

2022-01-13 20:20 UTC, gkalpak approved these changes

2022-01-14 17:26 UTC, Splaktar requested changes

2022-01-14 17:26 UTC, Splaktar commented on .npmrc
> +//registry.xlts.dev/:_authToken=PASTE_AUTH_TOKEN_HERE
```suggestion
```
We should just leave this blank. If the user has the token set up in their user `.npmrc` file or if they've (in our case) logged in via the npm CLI, then this isn't needed.

2022-01-14 17:26 UTC, Splaktar commented on README.md
> +
```suggestion
Make sure to you have configured your authentication with the XLTS.dev registry via
- supplying the token in the `.npmrc` file in your user home directory
- logging into the registry via the npm CLI

```

2022-01-17 19:29 UTC, Splaktar approved these changes

2022-01-17 19:30 UTC, merged